site_name: Открытые стандарты (спецификации) по методологии разработки
docs_dir: 'spec'
theme: 'material'
repo_name: 'ASMfreaK/rfc_translations'
repo_url: 'https://github.com/ASMfreaK/rfc_translations'
extra:
  palette:
    primary: 'cyan'
    accent: 'light green'
markdown_extensions:
    - pymdownx.tasklist(custom_checkbox=true)
pages:
    - 'Переводы различных RFC' : index.md
    - 'digistan.org' :
        - '1/КОСС' : 'digistan.org/1/КОСС.md'
    - 'rfc.zeromq.org' :
        - '42/К4' : 'rfc.zeromq.org/42/К4.md'
